clc;
clear all;
close all;
N = 50; n = 0:N - 1;
k = 0:N - 1;
n1 = 0:25;
xn = [n1 .* exp(-0.3 * n1) zeros(1, 24)];
WN = exp(-j * 2 * pi / N);
nk = n' * k;
WNnk = WN.^nk;
Xk = (xn * WNnk) / N;
magXk = abs([Xk(N / 2 + 2:N) Xk(1:N / 2 + 1)]);
phaseXk = angle([Xk(N / 2 + 2:N) Xk(1:N / 2 + 1)]);
k1 = [-N / 2 + 1:N / 2];
subplot(121);
stem(k1, magXk, 'filled');
xlabel('k');
ylabel('|Xk|');
title('Magnitude');
subplot(122);
stem(k1, phaseXk, 'filled');
xlabel('k');
ylabel('angleXk');
title('Phase');
